language: node_js
node_js:
 - "12.14"
branches:
  only:
  - master
before_script:
  - yarn install
deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "Us East"       
    app: "nextbackend"                     
    env: "Nextfrontend-env-1"                     
    on:
      branch: "master"

after_deploy:
  - echo "Application Deployed!"